"""
Django settings for hr_system project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging

os.environ["CHROMA_RUST_BINDINGS"] = "0"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p31q0&o^o(5pt*do3%-6acr_0=s)&6okdo_cxqenl-8@n%_0pe"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1","10.253.23.23","0.0.0.0"]

# ... your other settings ...

# Allow serving user-uploaded files during development
MEDIA_URL = '/uploaded_files/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'utils','data','docs')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ragsys",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hr_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'ragsys' / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hr_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'chatbotdb',
        'USER': 'chatbotuser',
        'PASSWORD': 'StrongPassword123',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'ragsys' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# LDAP Configuration
LDAP_SERVER = 'ldap://10.5.128.135'  # Your LDAP server IP
LDAP_PORT = 389  # Standard LDAP port
LDAP_USE_SSL = False  # Not using SSL
LDAP_USE_TLS = False  # Not using STARTTLS
LDAP_SEARCH_BASE = 'DC=itlab,DC=local'  # Your base DN
LDAP_SEARCH_FILTER = '(sAMAccountName={})'  # For Active Directory
LDAP_ATTRIBUTES = [
    'sAMAccountName', 'cn', 'mail', 'givenName', 
    'sn', 'department', 'title', 'memberOf',
    'distinguishedName', 'userPrincipalName'
]
LDAP_BIND_DN = 'ITLAB\maher'   # Use anonymous bind or specify service account
 

LDAP_BIND_PASSWORD = 'Password1'  # Leave empty if using anonymous bind
# LDAP User Mapping for Active Directory
LDAP_USER_MAPPING = {
    'username': 'sAMAccountName',
    'email': 'mail',
    'first_name': 'givenName',
    'last_name': 'sn',
}

# Optional: Cache LDAP results to reduce server load
LDAP_CACHE_TIMEOUT = 300  # 5 minutes cache
# # LDAP Configuration
# LDAP_SERVER = 'ldap://10.253.23.23'  # Change to your LDAP server
# LDAP_PORT = 389  # Use 636 for LDAPS
# LDAP_USE_SSL = False  # Set to True for LDAPS
# LDAP_USE_TLS = False  # Set to True for STARTTLS
# LDAP_SEARCH_BASE = 'dc=syriatel,dc=com'  # Adjust for your domain
# LDAP_SEARCH_FILTER = '(uid={})'  # Adjust based on your LDAP schema
# LDAP_ATTRIBUTES = ['uid', 'cn', 'mail', 'givenName', 'sn', 'department', 'title', 'memberOf']
# LDAP_BIND_DN = ''  # Leave empty for anonymous bind, or set to service account
# LDAP_BIND_PASSWORD = ''  # Leave empty if using anonymous bind
# LDAP_USER_MAPPING = {
#     'username': 'uid',
#     'email': 'mail',
#     'first_name': 'givenName',
#     'last_name': 'sn',
# }

# # Optional: Cache LDAP results to reduce server load
# LDAP_CACHE_TIMEOUT = 300  # 5 minutes cache

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'ragsys': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'ragsys.ldap_auth': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}