# Generated by Django 5.2.8 on 2026-01-27 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rag_mode', models.CharField(default='Preprocessed doc', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('show_thinking', models.BooleanField(default=False)),
                ('display_mode', models.CharField(choices=[('answer_only', 'Answer only'), ('answer_assumptions', 'Answer + assumptions'), ('full', 'Full reasoning')], default='answer_only', max_length=50)),
                ('message_count', models.IntegerField(default=0)),
                ('last_preview', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(default=0)),
                ('references', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ragsys.chatsession')),
            ],
            options={
                'ordering': ['session', 'sequence'],
            },
        ),
    ]
