# Generated by Django 5.2.8 on 2026-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='cumulative_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
